# Generated by Django 3.0.2 on 2020-01-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_cadet_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='attendancePercentage',
            field=models.FloatField(null=True),
        ),
    ]
