# Generated by Django 3.0.2 on 2020-01-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20200107_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='attendancePercentage',
        ),
    ]
