# Generated by Django 3.0.2 on 2020-01-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_flight_attendancepercentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadet',
            name='daysPresent',
        ),
        migrations.AddField(
            model_name='day',
            name='cadetsPresent',
            field=models.ManyToManyField(to='attendance.Cadet'),
        ),
    ]
