# Generated by Django 3.0.2 on 2020-01-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200107_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='dayName',
            field=models.CharField(default='Test 1', max_length=128),
            preserve_default=False,
        ),
    ]
